# Generated by Django 5.1.5 on 2025-02-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_ingredient_recipe_recipeingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
