# Generated by Django 5.1.5 on 2025-02-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0009_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashid', models.CharField(max_length=32, unique=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodgram.recipe')),
            ],
        ),
    ]
