# Generated by Django 5.1.5 on 2025-02-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0012_recipe_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
