name: Main Foodgram Workflow
on:
  push:
    branches:
      - dev
jobs:
  tests:

    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install ruff==0.8.0

    - name: Lint with ruff and tests
      run: |
        python -m ruff check backend/
        cd backend/
        python manage.py test